// GophKeeper API.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: gophkeeper/v1/gophkeeper.proto

package gophkeeperv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/gofeaturespb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// SecretType says what kind of data is inside the payload.
// The type is set at create time and cannot change.
type SecretType int32

const (
	SecretType_SECRET_TYPE_UNSPECIFIED    SecretType = 0
	SecretType_SECRET_TYPE_LOGIN_PASSWORD SecretType = 1
	SecretType_SECRET_TYPE_TEXT           SecretType = 2
	SecretType_SECRET_TYPE_BINARY         SecretType = 3
	SecretType_SECRET_TYPE_CARD           SecretType = 4
)

// Enum value maps for SecretType.
var (
	SecretType_name = map[int32]string{
		0: "SECRET_TYPE_UNSPECIFIED",
		1: "SECRET_TYPE_LOGIN_PASSWORD",
		2: "SECRET_TYPE_TEXT",
		3: "SECRET_TYPE_BINARY",
		4: "SECRET_TYPE_CARD",
	}
	SecretType_value = map[string]int32{
		"SECRET_TYPE_UNSPECIFIED":    0,
		"SECRET_TYPE_LOGIN_PASSWORD": 1,
		"SECRET_TYPE_TEXT":           2,
		"SECRET_TYPE_BINARY":         3,
		"SECRET_TYPE_CARD":           4,
	}
)

func (x SecretType) Enum() *SecretType {
	p := new(SecretType)
	*p = x
	return p
}

func (x SecretType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SecretType) Descriptor() protoreflect.EnumDescriptor {
	return file_gophkeeper_v1_gophkeeper_proto_enumTypes[0].Descriptor()
}

func (SecretType) Type() protoreflect.EnumType {
	return &file_gophkeeper_v1_gophkeeper_proto_enumTypes[0]
}

func (x SecretType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// KdfParams are the Argon2id settings used to derive the KEK
// from the master password. The client picks them at register
// time; the server stores and returns them as-is.
type KdfParams struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_MemoryKib   uint32                 `protobuf:"varint,1,opt,name=memory_kib,json=memoryKib"`
	xxx_hidden_Time        uint32                 `protobuf:"varint,2,opt,name=time"`
	xxx_hidden_Threads     uint32                 `protobuf:"varint,3,opt,name=threads"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *KdfParams) Reset() {
	*x = KdfParams{}
	mi := &file_gophkeeper_v1_gophkeeper_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KdfParams) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KdfParams) ProtoMessage() {}

func (x *KdfParams) ProtoReflect() protoreflect.Message {
	mi := &file_gophkeeper_v1_gophkeeper_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *KdfParams) GetMemoryKib() uint32 {
	if x != nil {
		return x.xxx_hidden_MemoryKib
	}
	return 0
}

func (x *KdfParams) GetTime() uint32 {
	if x != nil {
		return x.xxx_hidden_Time
	}
	return 0
}

func (x *KdfParams) GetThreads() uint32 {
	if x != nil {
		return x.xxx_hidden_Threads
	}
	return 0
}

func (x *KdfParams) SetMemoryKib(v uint32) {
	x.xxx_hidden_MemoryKib = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 3)
}

func (x *KdfParams) SetTime(v uint32) {
	x.xxx_hidden_Time = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 3)
}

func (x *KdfParams) SetThreads(v uint32) {
	x.xxx_hidden_Threads = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 2, 3)
}

func (x *KdfParams) HasMemoryKib() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *KdfParams) HasTime() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *KdfParams) HasThreads() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 2)
}

func (x *KdfParams) ClearMemoryKib() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_MemoryKib = 0
}

func (x *KdfParams) ClearTime() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_Time = 0
}

func (x *KdfParams) ClearThreads() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 2)
	x.xxx_hidden_Threads = 0
}

type KdfParams_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Memory size in KiB.
	MemoryKib *uint32
	// Number of passes over the memory.
	Time *uint32
	// Number of parallel threads.
	Threads *uint32
}

func (b0 KdfParams_builder) Build() *KdfParams {
	m0 := &KdfParams{}
	b, x := &b0, m0
	_, _ = b, x
	if b.MemoryKib != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 3)
		x.xxx_hidden_MemoryKib = *b.MemoryKib
	}
	if b.Time != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 3)
		x.xxx_hidden_Time = *b.Time
	}
	if b.Threads != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 2, 3)
		x.xxx_hidden_Threads = *b.Threads
	}
	return m0
}

type RegisterRequest struct {
	state                   protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Login        *string                `protobuf:"bytes,1,opt,name=login"`
	xxx_hidden_Password     *string                `protobuf:"bytes,2,opt,name=password"`
	xxx_hidden_KekSalt      []byte                 `protobuf:"bytes,3,opt,name=kek_salt,json=kekSalt"`
	xxx_hidden_KdfParams    *KdfParams             `protobuf:"bytes,4,opt,name=kdf_params,json=kdfParams"`
	xxx_hidden_EncryptedDek []byte                 `protobuf:"bytes,5,opt,name=encrypted_dek,json=encryptedDek"`
	XXX_raceDetectHookData  protoimpl.RaceDetectHookData
	XXX_presence            [1]uint32
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *RegisterRequest) Reset() {
	*x = RegisterRequest{}
	mi := &file_gophkeeper_v1_gophkeeper_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRequest) ProtoMessage() {}

func (x *RegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gophkeeper_v1_gophkeeper_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *RegisterRequest) GetLogin() string {
	if x != nil {
		if x.xxx_hidden_Login != nil {
			return *x.xxx_hidden_Login
		}
		return ""
	}
	return ""
}

func (x *RegisterRequest) GetPassword() string {
	if x != nil {
		if x.xxx_hidden_Password != nil {
			return *x.xxx_hidden_Password
		}
		return ""
	}
	return ""
}

func (x *RegisterRequest) GetKekSalt() []byte {
	if x != nil {
		return x.xxx_hidden_KekSalt
	}
	return nil
}

func (x *RegisterRequest) GetKdfParams() *KdfParams {
	if x != nil {
		return x.xxx_hidden_KdfParams
	}
	return nil
}

func (x *RegisterRequest) GetEncryptedDek() []byte {
	if x != nil {
		return x.xxx_hidden_EncryptedDek
	}
	return nil
}

func (x *RegisterRequest) SetLogin(v string) {
	x.xxx_hidden_Login = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 5)
}

func (x *RegisterRequest) SetPassword(v string) {
	x.xxx_hidden_Password = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 5)
}

func (x *RegisterRequest) SetKekSalt(v []byte) {
	if v == nil {
		v = []byte{}
	}
	x.xxx_hidden_KekSalt = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 2, 5)
}

func (x *RegisterRequest) SetKdfParams(v *KdfParams) {
	x.xxx_hidden_KdfParams = v
}

func (x *RegisterRequest) SetEncryptedDek(v []byte) {
	if v == nil {
		v = []byte{}
	}
	x.xxx_hidden_EncryptedDek = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 4, 5)
}

func (x *RegisterRequest) HasLogin() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *RegisterRequest) HasPassword() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *RegisterRequest) HasKekSalt() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 2)
}

func (x *RegisterRequest) HasKdfParams() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_KdfParams != nil
}

func (x *RegisterRequest) HasEncryptedDek() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 4)
}

func (x *RegisterRequest) ClearLogin() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Login = nil
}

func (x *RegisterRequest) ClearPassword() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_Password = nil
}

func (x *RegisterRequest) ClearKekSalt() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 2)
	x.xxx_hidden_KekSalt = nil
}

func (x *RegisterRequest) ClearKdfParams() {
	x.xxx_hidden_KdfParams = nil
}

func (x *RegisterRequest) ClearEncryptedDek() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 4)
	x.xxx_hidden_EncryptedDek = nil
}

type RegisterRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Login *string
	// Account password. It protects the account, not the data.
	// It must not be the master password.
	Password *string
	// Random salt for the KEK derivation.
	KekSalt   []byte
	KdfParams *KdfParams
	// DEK encrypted with the KEK (AES-256-GCM).
	EncryptedDek []byte
}

func (b0 RegisterRequest_builder) Build() *RegisterRequest {
	m0 := &RegisterRequest{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Login != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 5)
		x.xxx_hidden_Login = b.Login
	}
	if b.Password != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 5)
		x.xxx_hidden_Password = b.Password
	}
	if b.KekSalt != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 2, 5)
		x.xxx_hidden_KekSalt = b.KekSalt
	}
	x.xxx_hidden_KdfParams = b.KdfParams
	if b.EncryptedDek != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 4, 5)
		x.xxx_hidden_EncryptedDek = b.EncryptedDek
	}
	return m0
}

type RegisterResponse struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Token       *string                `protobuf:"bytes,1,opt,name=token"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *RegisterResponse) Reset() {
	*x = RegisterResponse{}
	mi := &file_gophkeeper_v1_gophkeeper_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterResponse) ProtoMessage() {}

func (x *RegisterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gophkeeper_v1_gophkeeper_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *RegisterResponse) GetToken() string {
	if x != nil {
		if x.xxx_hidden_Token != nil {
			return *x.xxx_hidden_Token
		}
		return ""
	}
	return ""
}

func (x *RegisterResponse) SetToken(v string) {
	x.xxx_hidden_Token = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 1)
}

func (x *RegisterResponse) HasToken() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *RegisterResponse) ClearToken() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Token = nil
}

type RegisterResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Token *string
}

func (b0 RegisterResponse_builder) Build() *RegisterResponse {
	m0 := &RegisterResponse{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Token != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 1)
		x.xxx_hidden_Token = b.Token
	}
	return m0
}

type LoginRequest struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Login       *string                `protobuf:"bytes,1,opt,name=login"`
	xxx_hidden_Password    *string                `protobuf:"bytes,2,opt,name=password"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *LoginRequest) Reset() {
	*x = LoginRequest{}
	mi := &file_gophkeeper_v1_gophkeeper_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginRequest) ProtoMessage() {}

func (x *LoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gophkeeper_v1_gophkeeper_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *LoginRequest) GetLogin() string {
	if x != nil {
		if x.xxx_hidden_Login != nil {
			return *x.xxx_hidden_Login
		}
		return ""
	}
	return ""
}

func (x *LoginRequest) GetPassword() string {
	if x != nil {
		if x.xxx_hidden_Password != nil {
			return *x.xxx_hidden_Password
		}
		return ""
	}
	return ""
}

func (x *LoginRequest) SetLogin(v string) {
	x.xxx_hidden_Login = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 2)
}

func (x *LoginRequest) SetPassword(v string) {
	x.xxx_hidden_Password = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 2)
}

func (x *LoginRequest) HasLogin() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *LoginRequest) HasPassword() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *LoginRequest) ClearLogin() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Login = nil
}

func (x *LoginRequest) ClearPassword() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_Password = nil
}

type LoginRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Login    *string
	Password *string
}

func (b0 LoginRequest_builder) Build() *LoginRequest {
	m0 := &LoginRequest{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Login != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 2)
		x.xxx_hidden_Login = b.Login
	}
	if b.Password != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 2)
		x.xxx_hidden_Password = b.Password
	}
	return m0
}

type LoginResponse struct {
	state                   protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Token        *string                `protobuf:"bytes,1,opt,name=token"`
	xxx_hidden_KekSalt      []byte                 `protobuf:"bytes,2,opt,name=kek_salt,json=kekSalt"`
	xxx_hidden_KdfParams    *KdfParams             `protobuf:"bytes,3,opt,name=kdf_params,json=kdfParams"`
	xxx_hidden_EncryptedDek []byte                 `protobuf:"bytes,4,opt,name=encrypted_dek,json=encryptedDek"`
	XXX_raceDetectHookData  protoimpl.RaceDetectHookData
	XXX_presence            [1]uint32
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *LoginResponse) Reset() {
	*x = LoginResponse{}
	mi := &file_gophkeeper_v1_gophkeeper_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginResponse) ProtoMessage() {}

func (x *LoginResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gophkeeper_v1_gophkeeper_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *LoginResponse) GetToken() string {
	if x != nil {
		if x.xxx_hidden_Token != nil {
			return *x.xxx_hidden_Token
		}
		return ""
	}
	return ""
}

func (x *LoginResponse) GetKekSalt() []byte {
	if x != nil {
		return x.xxx_hidden_KekSalt
	}
	return nil
}

func (x *LoginResponse) GetKdfParams() *KdfParams {
	if x != nil {
		return x.xxx_hidden_KdfParams
	}
	return nil
}

func (x *LoginResponse) GetEncryptedDek() []byte {
	if x != nil {
		return x.xxx_hidden_EncryptedDek
	}
	return nil
}

func (x *LoginResponse) SetToken(v string) {
	x.xxx_hidden_Token = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 4)
}

func (x *LoginResponse) SetKekSalt(v []byte) {
	if v == nil {
		v = []byte{}
	}
	x.xxx_hidden_KekSalt = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 4)
}

func (x *LoginResponse) SetKdfParams(v *KdfParams) {
	x.xxx_hidden_KdfParams = v
}

func (x *LoginResponse) SetEncryptedDek(v []byte) {
	if v == nil {
		v = []byte{}
	}
	x.xxx_hidden_EncryptedDek = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 3, 4)
}

func (x *LoginResponse) HasToken() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *LoginResponse) HasKekSalt() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *LoginResponse) HasKdfParams() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_KdfParams != nil
}

func (x *LoginResponse) HasEncryptedDek() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 3)
}

func (x *LoginResponse) ClearToken() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Token = nil
}

func (x *LoginResponse) ClearKekSalt() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_KekSalt = nil
}

func (x *LoginResponse) ClearKdfParams() {
	x.xxx_hidden_KdfParams = nil
}

func (x *LoginResponse) ClearEncryptedDek() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 3)
	x.xxx_hidden_EncryptedDek = nil
}

type LoginResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Token        *string
	KekSalt      []byte
	KdfParams    *KdfParams
	EncryptedDek []byte
}

func (b0 LoginResponse_builder) Build() *LoginResponse {
	m0 := &LoginResponse{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Token != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 4)
		x.xxx_hidden_Token = b.Token
	}
	if b.KekSalt != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 4)
		x.xxx_hidden_KekSalt = b.KekSalt
	}
	x.xxx_hidden_KdfParams = b.KdfParams
	if b.EncryptedDek != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 3, 4)
		x.xxx_hidden_EncryptedDek = b.EncryptedDek
	}
	return m0
}

// Secret is one stored record. The payload is an encrypted JSON
// blob with the name, the metadata and the type-specific fields.
// The server cannot read it.
type Secret struct {
	state                       protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Id               *string                `protobuf:"bytes,1,opt,name=id"`
	xxx_hidden_Type             SecretType             `protobuf:"varint,2,opt,name=type,enum=gophkeeper.v1.SecretType"`
	xxx_hidden_EncryptedPayload []byte                 `protobuf:"bytes,3,opt,name=encrypted_payload,json=encryptedPayload"`
	xxx_hidden_Version          int64                  `protobuf:"varint,4,opt,name=version"`
	xxx_hidden_CreatedAt        *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=created_at,json=createdAt"`
	xxx_hidden_UpdatedAt        *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=updated_at,json=updatedAt"`
	XXX_raceDetectHookData      protoimpl.RaceDetectHookData
	XXX_presence                [1]uint32
	unknownFields               protoimpl.UnknownFields
	sizeCache                   protoimpl.SizeCache
}

func (x *Secret) Reset() {
	*x = Secret{}
	mi := &file_gophkeeper_v1_gophkeeper_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Secret) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Secret) ProtoMessage() {}

func (x *Secret) ProtoReflect() protoreflect.Message {
	mi := &file_gophkeeper_v1_gophkeeper_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *Secret) GetId() string {
	if x != nil {
		if x.xxx_hidden_Id != nil {
			return *x.xxx_hidden_Id
		}
		return ""
	}
	return ""
}

func (x *Secret) GetType() SecretType {
	if x != nil {
		if protoimpl.X.Present(&(x.XXX_presence[0]), 1) {
			return x.xxx_hidden_Type
		}
	}
	return SecretType_SECRET_TYPE_UNSPECIFIED
}

func (x *Secret) GetEncryptedPayload() []byte {
	if x != nil {
		return x.xxx_hidden_EncryptedPayload
	}
	return nil
}

func (x *Secret) GetVersion() int64 {
	if x != nil {
		return x.xxx_hidden_Version
	}
	return 0
}

func (x *Secret) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.xxx_hidden_CreatedAt
	}
	return nil
}

func (x *Secret) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.xxx_hidden_UpdatedAt
	}
	return nil
}

func (x *Secret) SetId(v string) {
	x.xxx_hidden_Id = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 6)
}

func (x *Secret) SetType(v SecretType) {
	x.xxx_hidden_Type = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 6)
}

func (x *Secret) SetEncryptedPayload(v []byte) {
	if v == nil {
		v = []byte{}
	}
	x.xxx_hidden_EncryptedPayload = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 2, 6)
}

func (x *Secret) SetVersion(v int64) {
	x.xxx_hidden_Version = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 3, 6)
}

func (x *Secret) SetCreatedAt(v *timestamppb.Timestamp) {
	x.xxx_hidden_CreatedAt = v
}

func (x *Secret) SetUpdatedAt(v *timestamppb.Timestamp) {
	x.xxx_hidden_UpdatedAt = v
}

func (x *Secret) HasId() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *Secret) HasType() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *Secret) HasEncryptedPayload() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 2)
}

func (x *Secret) HasVersion() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 3)
}

func (x *Secret) HasCreatedAt() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_CreatedAt != nil
}

func (x *Secret) HasUpdatedAt() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_UpdatedAt != nil
}

func (x *Secret) ClearId() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Id = nil
}

func (x *Secret) ClearType() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_Type = SecretType_SECRET_TYPE_UNSPECIFIED
}

func (x *Secret) ClearEncryptedPayload() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 2)
	x.xxx_hidden_EncryptedPayload = nil
}

func (x *Secret) ClearVersion() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 3)
	x.xxx_hidden_Version = 0
}

func (x *Secret) ClearCreatedAt() {
	x.xxx_hidden_CreatedAt = nil
}

func (x *Secret) ClearUpdatedAt() {
	x.xxx_hidden_UpdatedAt = nil
}

type Secret_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Id               *string
	Type             *SecretType
	EncryptedPayload []byte
	// Grows on every update. Informational only, see SecretsService.
	Version   *int64
	CreatedAt *timestamppb.Timestamp
	UpdatedAt *timestamppb.Timestamp
}

func (b0 Secret_builder) Build() *Secret {
	m0 := &Secret{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Id != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 6)
		x.xxx_hidden_Id = b.Id
	}
	if b.Type != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 6)
		x.xxx_hidden_Type = *b.Type
	}
	if b.EncryptedPayload != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 2, 6)
		x.xxx_hidden_EncryptedPayload = b.EncryptedPayload
	}
	if b.Version != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 3, 6)
		x.xxx_hidden_Version = *b.Version
	}
	x.xxx_hidden_CreatedAt = b.CreatedAt
	x.xxx_hidden_UpdatedAt = b.UpdatedAt
	return m0
}

type CreateSecretRequest struct {
	state                       protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Type             SecretType             `protobuf:"varint,1,opt,name=type,enum=gophkeeper.v1.SecretType"`
	xxx_hidden_EncryptedPayload []byte                 `protobuf:"bytes,2,opt,name=encrypted_payload,json=encryptedPayload"`
	XXX_raceDetectHookData      protoimpl.RaceDetectHookData
	XXX_presence                [1]uint32
	unknownFields               protoimpl.UnknownFields
	sizeCache                   protoimpl.SizeCache
}

func (x *CreateSecretRequest) Reset() {
	*x = CreateSecretRequest{}
	mi := &file_gophkeeper_v1_gophkeeper_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSecretRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSecretRequest) ProtoMessage() {}

func (x *CreateSecretRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gophkeeper_v1_gophkeeper_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *CreateSecretRequest) GetType() SecretType {
	if x != nil {
		if protoimpl.X.Present(&(x.XXX_presence[0]), 0) {
			return x.xxx_hidden_Type
		}
	}
	return SecretType_SECRET_TYPE_UNSPECIFIED
}

func (x *CreateSecretRequest) GetEncryptedPayload() []byte {
	if x != nil {
		return x.xxx_hidden_EncryptedPayload
	}
	return nil
}

func (x *CreateSecretRequest) SetType(v SecretType) {
	x.xxx_hidden_Type = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 2)
}

func (x *CreateSecretRequest) SetEncryptedPayload(v []byte) {
	if v == nil {
		v = []byte{}
	}
	x.xxx_hidden_EncryptedPayload = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 2)
}

func (x *CreateSecretRequest) HasType() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *CreateSecretRequest) HasEncryptedPayload() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *CreateSecretRequest) ClearType() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Type = SecretType_SECRET_TYPE_UNSPECIFIED
}

func (x *CreateSecretRequest) ClearEncryptedPayload() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_EncryptedPayload = nil
}

type CreateSecretRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Type             *SecretType
	EncryptedPayload []byte
}

func (b0 CreateSecretRequest_builder) Build() *CreateSecretRequest {
	m0 := &CreateSecretRequest{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Type != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 2)
		x.xxx_hidden_Type = *b.Type
	}
	if b.EncryptedPayload != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 2)
		x.xxx_hidden_EncryptedPayload = b.EncryptedPayload
	}
	return m0
}

type CreateSecretResponse struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Id          *string                `protobuf:"bytes,1,opt,name=id"`
	xxx_hidden_Version     int64                  `protobuf:"varint,2,opt,name=version"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *CreateSecretResponse) Reset() {
	*x = CreateSecretResponse{}
	mi := &file_gophkeeper_v1_gophkeeper_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSecretResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSecretResponse) ProtoMessage() {}

func (x *CreateSecretResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gophkeeper_v1_gophkeeper_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *CreateSecretResponse) GetId() string {
	if x != nil {
		if x.xxx_hidden_Id != nil {
			return *x.xxx_hidden_Id
		}
		return ""
	}
	return ""
}

func (x *CreateSecretResponse) GetVersion() int64 {
	if x != nil {
		return x.xxx_hidden_Version
	}
	return 0
}

func (x *CreateSecretResponse) SetId(v string) {
	x.xxx_hidden_Id = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 2)
}

func (x *CreateSecretResponse) SetVersion(v int64) {
	x.xxx_hidden_Version = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 2)
}

func (x *CreateSecretResponse) HasId() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *CreateSecretResponse) HasVersion() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *CreateSecretResponse) ClearId() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Id = nil
}

func (x *CreateSecretResponse) ClearVersion() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_Version = 0
}

type CreateSecretResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Id      *string
	Version *int64
}

func (b0 CreateSecretResponse_builder) Build() *CreateSecretResponse {
	m0 := &CreateSecretResponse{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Id != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 2)
		x.xxx_hidden_Id = b.Id
	}
	if b.Version != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 2)
		x.xxx_hidden_Version = *b.Version
	}
	return m0
}

type GetSecretRequest struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Id          *string                `protobuf:"bytes,1,opt,name=id"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *GetSecretRequest) Reset() {
	*x = GetSecretRequest{}
	mi := &file_gophkeeper_v1_gophkeeper_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSecretRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSecretRequest) ProtoMessage() {}

func (x *GetSecretRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gophkeeper_v1_gophkeeper_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *GetSecretRequest) GetId() string {
	if x != nil {
		if x.xxx_hidden_Id != nil {
			return *x.xxx_hidden_Id
		}
		return ""
	}
	return ""
}

func (x *GetSecretRequest) SetId(v string) {
	x.xxx_hidden_Id = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 1)
}

func (x *GetSecretRequest) HasId() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *GetSecretRequest) ClearId() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Id = nil
}

type GetSecretRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Id *string
}

func (b0 GetSecretRequest_builder) Build() *GetSecretRequest {
	m0 := &GetSecretRequest{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Id != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 1)
		x.xxx_hidden_Id = b.Id
	}
	return m0
}

type GetSecretResponse struct {
	state             protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Secret *Secret                `protobuf:"bytes,1,opt,name=secret"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *GetSecretResponse) Reset() {
	*x = GetSecretResponse{}
	mi := &file_gophkeeper_v1_gophkeeper_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSecretResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSecretResponse) ProtoMessage() {}

func (x *GetSecretResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gophkeeper_v1_gophkeeper_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *GetSecretResponse) GetSecret() *Secret {
	if x != nil {
		return x.xxx_hidden_Secret
	}
	return nil
}

func (x *GetSecretResponse) SetSecret(v *Secret) {
	x.xxx_hidden_Secret = v
}

func (x *GetSecretResponse) HasSecret() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Secret != nil
}

func (x *GetSecretResponse) ClearSecret() {
	x.xxx_hidden_Secret = nil
}

type GetSecretResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Secret *Secret
}

func (b0 GetSecretResponse_builder) Build() *GetSecretResponse {
	m0 := &GetSecretResponse{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Secret = b.Secret
	return m0
}

type ListSecretsRequest struct {
	state         protoimpl.MessageState `protogen:"opaque.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSecretsRequest) Reset() {
	*x = ListSecretsRequest{}
	mi := &file_gophkeeper_v1_gophkeeper_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSecretsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSecretsRequest) ProtoMessage() {}

func (x *ListSecretsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gophkeeper_v1_gophkeeper_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

type ListSecretsRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

}

func (b0 ListSecretsRequest_builder) Build() *ListSecretsRequest {
	m0 := &ListSecretsRequest{}
	b, x := &b0, m0
	_, _ = b, x
	return m0
}

type ListSecretsResponse struct {
	state              protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Secrets *[]*Secret             `protobuf:"bytes,1,rep,name=secrets"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *ListSecretsResponse) Reset() {
	*x = ListSecretsResponse{}
	mi := &file_gophkeeper_v1_gophkeeper_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSecretsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSecretsResponse) ProtoMessage() {}

func (x *ListSecretsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gophkeeper_v1_gophkeeper_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ListSecretsResponse) GetSecrets() []*Secret {
	if x != nil {
		if x.xxx_hidden_Secrets != nil {
			return *x.xxx_hidden_Secrets
		}
	}
	return nil
}

func (x *ListSecretsResponse) SetSecrets(v []*Secret) {
	x.xxx_hidden_Secrets = &v
}

type ListSecretsResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Secrets []*Secret
}

func (b0 ListSecretsResponse_builder) Build() *ListSecretsResponse {
	m0 := &ListSecretsResponse{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Secrets = &b.Secrets
	return m0
}

type UpdateSecretRequest struct {
	state                       protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Id               *string                `protobuf:"bytes,1,opt,name=id"`
	xxx_hidden_EncryptedPayload []byte                 `protobuf:"bytes,2,opt,name=encrypted_payload,json=encryptedPayload"`
	XXX_raceDetectHookData      protoimpl.RaceDetectHookData
	XXX_presence                [1]uint32
	unknownFields               protoimpl.UnknownFields
	sizeCache                   protoimpl.SizeCache
}

func (x *UpdateSecretRequest) Reset() {
	*x = UpdateSecretRequest{}
	mi := &file_gophkeeper_v1_gophkeeper_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateSecretRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateSecretRequest) ProtoMessage() {}

func (x *UpdateSecretRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gophkeeper_v1_gophkeeper_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *UpdateSecretRequest) GetId() string {
	if x != nil {
		if x.xxx_hidden_Id != nil {
			return *x.xxx_hidden_Id
		}
		return ""
	}
	return ""
}

func (x *UpdateSecretRequest) GetEncryptedPayload() []byte {
	if x != nil {
		return x.xxx_hidden_EncryptedPayload
	}
	return nil
}

func (x *UpdateSecretRequest) SetId(v string) {
	x.xxx_hidden_Id = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 2)
}

func (x *UpdateSecretRequest) SetEncryptedPayload(v []byte) {
	if v == nil {
		v = []byte{}
	}
	x.xxx_hidden_EncryptedPayload = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 2)
}

func (x *UpdateSecretRequest) HasId() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *UpdateSecretRequest) HasEncryptedPayload() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *UpdateSecretRequest) ClearId() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Id = nil
}

func (x *UpdateSecretRequest) ClearEncryptedPayload() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_EncryptedPayload = nil
}

type UpdateSecretRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Id               *string
	EncryptedPayload []byte
}

func (b0 UpdateSecretRequest_builder) Build() *UpdateSecretRequest {
	m0 := &UpdateSecretRequest{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Id != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 2)
		x.xxx_hidden_Id = b.Id
	}
	if b.EncryptedPayload != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 2)
		x.xxx_hidden_EncryptedPayload = b.EncryptedPayload
	}
	return m0
}

type UpdateSecretResponse struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Version     int64                  `protobuf:"varint,1,opt,name=version"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *UpdateSecretResponse) Reset() {
	*x = UpdateSecretResponse{}
	mi := &file_gophkeeper_v1_gophkeeper_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateSecretResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateSecretResponse) ProtoMessage() {}

func (x *UpdateSecretResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gophkeeper_v1_gophkeeper_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *UpdateSecretResponse) GetVersion() int64 {
	if x != nil {
		return x.xxx_hidden_Version
	}
	return 0
}

func (x *UpdateSecretResponse) SetVersion(v int64) {
	x.xxx_hidden_Version = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 1)
}

func (x *UpdateSecretResponse) HasVersion() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *UpdateSecretResponse) ClearVersion() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Version = 0
}

type UpdateSecretResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Version *int64
}

func (b0 UpdateSecretResponse_builder) Build() *UpdateSecretResponse {
	m0 := &UpdateSecretResponse{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Version != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 1)
		x.xxx_hidden_Version = *b.Version
	}
	return m0
}

type DeleteSecretRequest struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Id          *string                `protobuf:"bytes,1,opt,name=id"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *DeleteSecretRequest) Reset() {
	*x = DeleteSecretRequest{}
	mi := &file_gophkeeper_v1_gophkeeper_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteSecretRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteSecretRequest) ProtoMessage() {}

func (x *DeleteSecretRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gophkeeper_v1_gophkeeper_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *DeleteSecretRequest) GetId() string {
	if x != nil {
		if x.xxx_hidden_Id != nil {
			return *x.xxx_hidden_Id
		}
		return ""
	}
	return ""
}

func (x *DeleteSecretRequest) SetId(v string) {
	x.xxx_hidden_Id = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 1)
}

func (x *DeleteSecretRequest) HasId() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *DeleteSecretRequest) ClearId() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Id = nil
}

type DeleteSecretRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Id *string
}

func (b0 DeleteSecretRequest_builder) Build() *DeleteSecretRequest {
	m0 := &DeleteSecretRequest{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Id != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 1)
		x.xxx_hidden_Id = b.Id
	}
	return m0
}

type DeleteSecretResponse struct {
	state         protoimpl.MessageState `protogen:"opaque.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteSecretResponse) Reset() {
	*x = DeleteSecretResponse{}
	mi := &file_gophkeeper_v1_gophkeeper_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteSecretResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteSecretResponse) ProtoMessage() {}

func (x *DeleteSecretResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gophkeeper_v1_gophkeeper_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

type DeleteSecretResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

}

func (b0 DeleteSecretResponse_builder) Build() *DeleteSecretResponse {
	m0 := &DeleteSecretResponse{}
	b, x := &b0, m0
	_, _ = b, x
	return m0
}

var File_gophkeeper_v1_gophkeeper_proto protoreflect.FileDescriptor

const file_gophkeeper_v1_gophkeeper_proto_rawDesc = "" +
	"\n" +
	"\x1egophkeeper/v1/gophkeeper.proto\x12\rgophkeeper.v1\x1a!google/protobuf/go_features.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"X\n" +
	"\tKdfParams\x12\x1d\n" +
	"\n" +
	"memory_kib\x18\x01 \x01(\rR\tmemoryKib\x12\x12\n" +
	"\x04time\x18\x02 \x01(\rR\x04time\x12\x18\n" +
	"\athreads\x18\x03 \x01(\rR\athreads\"\xbc\x01\n" +
	"\x0fRegisterRequest\x12\x14\n" +
	"\x05login\x18\x01 \x01(\tR\x05login\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\x12\x19\n" +
	"\bkek_salt\x18\x03 \x01(\fR\akekSalt\x127\n" +
	"\n" +
	"kdf_params\x18\x04 \x01(\v2\x18.gophkeeper.v1.KdfParamsR\tkdfParams\x12#\n" +
	"\rencrypted_dek\x18\x05 \x01(\fR\fencryptedDek\"(\n" +
	"\x10RegisterResponse\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\"@\n" +
	"\fLoginRequest\x12\x14\n" +
	"\x05login\x18\x01 \x01(\tR\x05login\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\"\x9e\x01\n" +
	"\rLoginResponse\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\x12\x19\n" +
	"\bkek_salt\x18\x02 \x01(\fR\akekSalt\x127\n" +
	"\n" +
	"kdf_params\x18\x03 \x01(\v2\x18.gophkeeper.v1.KdfParamsR\tkdfParams\x12#\n" +
	"\rencrypted_dek\x18\x04 \x01(\fR\fencryptedDek\"\x84\x02\n" +
	"\x06Secret\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12-\n" +
	"\x04type\x18\x02 \x01(\x0e2\x19.gophkeeper.v1.SecretTypeR\x04type\x12+\n" +
	"\x11encrypted_payload\x18\x03 \x01(\fR\x10encryptedPayload\x12\x18\n" +
	"\aversion\x18\x04 \x01(\x03R\aversion\x129\n" +
	"\n" +
	"created_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"q\n" +
	"\x13CreateSecretRequest\x12-\n" +
	"\x04type\x18\x01 \x01(\x0e2\x19.gophkeeper.v1.SecretTypeR\x04type\x12+\n" +
	"\x11encrypted_payload\x18\x02 \x01(\fR\x10encryptedPayload\"@\n" +
	"\x14CreateSecretResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x18\n" +
	"\aversion\x18\x02 \x01(\x03R\aversion\"\"\n" +
	"\x10GetSecretRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"B\n" +
	"\x11GetSecretResponse\x12-\n" +
	"\x06secret\x18\x01 \x01(\v2\x15.gophkeeper.v1.SecretR\x06secret\"\x14\n" +
	"\x12ListSecretsRequest\"F\n" +
	"\x13ListSecretsResponse\x12/\n" +
	"\asecrets\x18\x01 \x03(\v2\x15.gophkeeper.v1.SecretR\asecrets\"R\n" +
	"\x13UpdateSecretRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12+\n" +
	"\x11encrypted_payload\x18\x02 \x01(\fR\x10encryptedPayload\"0\n" +
	"\x14UpdateSecretResponse\x12\x18\n" +
	"\aversion\x18\x01 \x01(\x03R\aversion\"%\n" +
	"\x13DeleteSecretRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\x16\n" +
	"\x14DeleteSecretResponse*\x8d\x01\n" +
	"\n" +
	"SecretType\x12\x1b\n" +
	"\x17SECRET_TYPE_UNSPECIFIED\x10\x00\x12\x1e\n" +
	"\x1aSECRET_TYPE_LOGIN_PASSWORD\x10\x01\x12\x14\n" +
	"\x10SECRET_TYPE_TEXT\x10\x02\x12\x16\n" +
	"\x12SECRET_TYPE_BINARY\x10\x03\x12\x14\n" +
	"\x10SECRET_TYPE_CARD\x10\x042\x9e\x01\n" +
	"\vAuthService\x12K\n" +
	"\bRegister\x12\x1e.gophkeeper.v1.RegisterRequest\x1a\x1f.gophkeeper.v1.RegisterResponse\x12B\n" +
	"\x05Login\x12\x1b.gophkeeper.v1.LoginRequest\x1a\x1c.gophkeeper.v1.LoginResponse2\xc1\x03\n" +
	"\x0eSecretsService\x12W\n" +
	"\fCreateSecret\x12\".gophkeeper.v1.CreateSecretRequest\x1a#.gophkeeper.v1.CreateSecretResponse\x12N\n" +
	"\tGetSecret\x12\x1f.gophkeeper.v1.GetSecretRequest\x1a .gophkeeper.v1.GetSecretResponse\x12T\n" +
	"\vListSecrets\x12!.gophkeeper.v1.ListSecretsRequest\x1a\".gophkeeper.v1.ListSecretsResponse\x12W\n" +
	"\fUpdateSecret\x12\".gophkeeper.v1.UpdateSecretRequest\x1a#.gophkeeper.v1.UpdateSecretResponse\x12W\n" +
	"\fDeleteSecret\x12\".gophkeeper.v1.DeleteSecretRequest\x1a#.gophkeeper.v1.DeleteSecretResponseBMZCgithub.com/ustasjs/goph-keeper/pkg/proto/gophkeeper/v1;gophkeeperv1\x92\x03\x05\xd2>\x02\x10\x03b\beditionsp\xe8\a"

var file_gophkeeper_v1_gophkeeper_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_gophkeeper_v1_gophkeeper_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_gophkeeper_v1_gophkeeper_proto_goTypes = []any{
	(SecretType)(0),               // 0: gophkeeper.v1.SecretType
	(*KdfParams)(nil),             // 1: gophkeeper.v1.KdfParams
	(*RegisterRequest)(nil),       // 2: gophkeeper.v1.RegisterRequest
	(*RegisterResponse)(nil),      // 3: gophkeeper.v1.RegisterResponse
	(*LoginRequest)(nil),          // 4: gophkeeper.v1.LoginRequest
	(*LoginResponse)(nil),         // 5: gophkeeper.v1.LoginResponse
	(*Secret)(nil),                // 6: gophkeeper.v1.Secret
	(*CreateSecretRequest)(nil),   // 7: gophkeeper.v1.CreateSecretRequest
	(*CreateSecretResponse)(nil),  // 8: gophkeeper.v1.CreateSecretResponse
	(*GetSecretRequest)(nil),      // 9: gophkeeper.v1.GetSecretRequest
	(*GetSecretResponse)(nil),     // 10: gophkeeper.v1.GetSecretResponse
	(*ListSecretsRequest)(nil),    // 11: gophkeeper.v1.ListSecretsRequest
	(*ListSecretsResponse)(nil),   // 12: gophkeeper.v1.ListSecretsResponse
	(*UpdateSecretRequest)(nil),   // 13: gophkeeper.v1.UpdateSecretRequest
	(*UpdateSecretResponse)(nil),  // 14: gophkeeper.v1.UpdateSecretResponse
	(*DeleteSecretRequest)(nil),   // 15: gophkeeper.v1.DeleteSecretRequest
	(*DeleteSecretResponse)(nil),  // 16: gophkeeper.v1.DeleteSecretResponse
	(*timestamppb.Timestamp)(nil), // 17: google.protobuf.Timestamp
}
var file_gophkeeper_v1_gophkeeper_proto_depIdxs = []int32{
	1,  // 0: gophkeeper.v1.RegisterRequest.kdf_params:type_name -> gophkeeper.v1.KdfParams
	1,  // 1: gophkeeper.v1.LoginResponse.kdf_params:type_name -> gophkeeper.v1.KdfParams
	0,  // 2: gophkeeper.v1.Secret.type:type_name -> gophkeeper.v1.SecretType
	17, // 3: gophkeeper.v1.Secret.created_at:type_name -> google.protobuf.Timestamp
	17, // 4: gophkeeper.v1.Secret.updated_at:type_name -> google.protobuf.Timestamp
	0,  // 5: gophkeeper.v1.CreateSecretRequest.type:type_name -> gophkeeper.v1.SecretType
	6,  // 6: gophkeeper.v1.GetSecretResponse.secret:type_name -> gophkeeper.v1.Secret
	6,  // 7: gophkeeper.v1.ListSecretsResponse.secrets:type_name -> gophkeeper.v1.Secret
	2,  // 8: gophkeeper.v1.AuthService.Register:input_type -> gophkeeper.v1.RegisterRequest
	4,  // 9: gophkeeper.v1.AuthService.Login:input_type -> gophkeeper.v1.LoginRequest
	7,  // 10: gophkeeper.v1.SecretsService.CreateSecret:input_type -> gophkeeper.v1.CreateSecretRequest
	9,  // 11: gophkeeper.v1.SecretsService.GetSecret:input_type -> gophkeeper.v1.GetSecretRequest
	11, // 12: gophkeeper.v1.SecretsService.ListSecrets:input_type -> gophkeeper.v1.ListSecretsRequest
	13, // 13: gophkeeper.v1.SecretsService.UpdateSecret:input_type -> gophkeeper.v1.UpdateSecretRequest
	15, // 14: gophkeeper.v1.SecretsService.DeleteSecret:input_type -> gophkeeper.v1.DeleteSecretRequest
	3,  // 15: gophkeeper.v1.AuthService.Register:output_type -> gophkeeper.v1.RegisterResponse
	5,  // 16: gophkeeper.v1.AuthService.Login:output_type -> gophkeeper.v1.LoginResponse
	8,  // 17: gophkeeper.v1.SecretsService.CreateSecret:output_type -> gophkeeper.v1.CreateSecretResponse
	10, // 18: gophkeeper.v1.SecretsService.GetSecret:output_type -> gophkeeper.v1.GetSecretResponse
	12, // 19: gophkeeper.v1.SecretsService.ListSecrets:output_type -> gophkeeper.v1.ListSecretsResponse
	14, // 20: gophkeeper.v1.SecretsService.UpdateSecret:output_type -> gophkeeper.v1.UpdateSecretResponse
	16, // 21: gophkeeper.v1.SecretsService.DeleteSecret:output_type -> gophkeeper.v1.DeleteSecretResponse
	15, // [15:22] is the sub-list for method output_type
	8,  // [8:15] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_gophkeeper_v1_gophkeeper_proto_init() }
func file_gophkeeper_v1_gophkeeper_proto_init() {
	if File_gophkeeper_v1_gophkeeper_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_gophkeeper_v1_gophkeeper_proto_rawDesc), len(file_gophkeeper_v1_gophkeeper_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_gophkeeper_v1_gophkeeper_proto_goTypes,
		DependencyIndexes: file_gophkeeper_v1_gophkeeper_proto_depIdxs,
		EnumInfos:         file_gophkeeper_v1_gophkeeper_proto_enumTypes,
		MessageInfos:      file_gophkeeper_v1_gophkeeper_proto_msgTypes,
	}.Build()
	File_gophkeeper_v1_gophkeeper_proto = out.File
	file_gophkeeper_v1_gophkeeper_proto_goTypes = nil
	file_gophkeeper_v1_gophkeeper_proto_depIdxs = nil
}
